! DESCRIP.MMS - build GNU patch for OpenVMS (IA64, x86-64)
!
! Run from the top of the prepared source tree via [.VMS]BUILD.COM, which
! passes ARCH (IA64 or X86_64) and creates the output directories.  Source
! lists and per-object rules come from [.VMS]SOURCES.MMS, generated by
! tools/prepare.sh on the host.

.IFDEF ARCH
.ELSE
ARCH = IA64
.ENDIF

OBJ = [.OBJ_$(ARCH)]
LOBJ = [.OBJ_$(ARCH).LIB]
BIN = [.BIN_$(ARCH)]

.INCLUDE [.VMS]SOURCES.MMS

LIB = $(OBJ)LIBPATCH.OLB
EXE = $(BIN)PATCH.EXE

CC = CC
! ENABLE_MERGE: src/Makefile.am adds it to AM_CPPFLAGS when merge.c is
! built (configure's default, --enable-merge).
CFLAGS = $(CC_QUAL)/NOLIST/INCLUDE_DIRECTORY=("./lib","./src","./vms")-
	/DEFINE=($(CC_DEFS),HAVE_CONFIG_H,ENABLE_MERGE)

ALL : $(EXE)
	@ CONTINUE

! "-": LINK ends with a warning status (%ILINK-W-COMPWARN) when modules
! compiled with VSI C's benign warnings; tools/build.sh fails the build on
! real link errors and undefined symbols.
$(EXE) : $(SRC_OBJS), $(EXTRA_OBJS), $(LIB)
	- LINK/EXECUTABLE=$(MMS$TARGET)/MAP=$(OBJ)PATCH.MAP/FULL $(SRC_OBJS), $(EXTRA_OBJS), $(LIB)/LIBRARY

! "-": LIBRARY ends with a warning status (%LIBRAR-W-COMCOD) for modules
! compiled with warnings.
$(LIB) : $(LIB_OBJS)
	IF F$SEARCH("$(MMS$TARGET)") .EQS. "" THEN LIBRARY/CREATE/OBJECT $(MMS$TARGET)
	- LIBRARY/REPLACE/OBJECT $(MMS$TARGET) $(LOBJ)*.OBJ

CLEAN :
	IF F$SEARCH("$(LOBJ)*.*") .NES. "" THEN DELETE/NOLOG $(LOBJ)*.*;*
	IF F$SEARCH("$(OBJ)*.OBJ") .NES. "" THEN DELETE/NOLOG $(OBJ)*.OBJ;*,*.OLB;*,*.MAP;*
	IF F$SEARCH("$(BIN)*.*") .NES. "" THEN DELETE/NOLOG $(BIN)*.*;*
